### ISSUE TITLE
Bibtex improvements

### ISSUE THREAD

**Issue by antagomir** [openresearchlabs/openresearchlabs.github.io#78]
The following would help:

1. Add `keyword` field to every bibtex record. When not clear what the category should be, use `keyword = {other},`

2. Use `status` field to highlight preprints: `status = {preprint},` - this will allow us to use the right keywords also for preprints (which would not work if "preprint" info was on the keywords field (?)).

3. Enable the selection of preprints based on the status field in [preprint page](http://datascience.utu.fi/research/preprints/)

**Comment by pitkant** [comment]
See develop-branch and my answer to #79

1. Every record has a keywords-field now. Some had two and these need review:

- [ ] Lahti17phos: open science and dh
- [ ] OKeefe15: gut and bioscience
- [ ] Lahti13icml: dh and datascience
- [ ] Tolonen15EnnenNyt: dh and dh (I took the liberty of removing the other field already)

2. In bibtex file "status" field should be inputed as "pubstate" for pandoc citeproc to understand it correctly. Some publications now have pubstate field, some have "preprint" as keyword that would be better suited in the pubstate field.

These need a correct keyword:
- [ ] Liu2021liver
- [ ] Ruuskanen2021diabetes
- [ ] Qin2021
- [ ] Zhu2021

3. Done, can be done with {{< articles status = "preprint" >}} now. See preprints.md for reference.
 
I will work to further refine this so that you could select articles with certain keyword and certain status, like this: {{< articles keyword = "dh" status = "preprint" >}}

**Comment by antagomir** [comment]
I have now fixed many of these in PR #80 

- removed duplicate keywords
- replaced status with pubstate and use this to refer to preprints only

There is not "status" field any more now. But if it works with status, it would probably also work that way with the field howpublished, which is relevant as well. or can we have multiple keywords; either in the same field separated by comma; or in different fields as keyword, keyword2 etc.?

I did not find Ruuskanen2021diabetes nor Qin2021 from master branch version of lahti.bib file. In which branch I can find these?

**Comment by pitkant** [comment]
The way it works is that BibLaTeX field "pubstate" is transformed to "status" in the json file. But if there is a "status" field in the BibLaTeX file pandoc citeproc does not know how to process this unstandard field and it gets left out of the json output.

I don't know if there is a table that would clearly show how fields are transformed between .bib files and .json files. Searching through man pages and similar resources did not provide much information. I found this [BibLaTeX cheat sheet](http://tug.ctan.org/info/biblatex-cheatsheet/biblatex-cheatsheet.pdf) useful in seeing what fields are in the standard.

Ruuskanen2021diabetes and Qin2021 were in lahti.bib file in the develop branch: https://github.com/openresearchlabs/openresearchlabs.github.io/blob/develop/content/publication_resources/bibtex/lahti.bib

**Comment by pitkant** [comment]
> can we have multiple keywords; either in the same field separated by comma; or in different fields as keyword, keyword2 etc.?

Multiple fields, no. The answer is the same as above: BibLaTeX specification does not know a field called "keyword2" and therefore pandoc citeproc cannot translate this odd field to json/yaml. It will be lost in translation.

Multiple keywords in same field, separated by comma. Yes. Printing out publication information about an item that has multiple keywords is now possible, **one keyword at a time**. In current bib file there is one item with multiple keywords, Lahti10thesis, which has been handy for testing. Its keywords are:

keywords = {thesis, probabilistic models, Bayesian analysis, data integration, gene expression, microarrays, computational science, data analysis, machine learning, computational biology, open source, open access, creative commons}

In the past this could be printed only by using the whole string as an exact match, like this:

{{< articles keyword = "thesis, probabilistic models, Bayesian analysis, data integration, gene expression, microarrays, computational science, data analysis, machine learning, computational biology, open source, open access, creative commons" >}}

Now it is possible to print the article by any of these individual keywords, like this:

{{< articles keyword = "thesis" >}}
{{< articles keyword = "probabilistic models" >}}
{{< articles keyword = "Bayesian analysis" >}}
...
{{< articles keyword = "creative commons" >}}

Apparently this also works, since the items are neighbours:

{{< articles keyword = "thesis, probabilistic models" >}}

But **this does not work**:

{{< articles keyword = "thesis, creative commons" >}}

**Comment by antagomir** [comment]
Ok very nice!

I think this issue can be closed if everything is ready(?). 

The Ruuskanen2021diabetes and Qin2021 could be moved from devel on the same go, or I can do it after this is closed, whichever easiest.
